language: go

go:
  - 1.8.3

script: 
  - go get github.com/stretchr/testify/assert
  - go test
  - go build
  - rm main
 
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash