name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    # install cmocka
    - name: install cmocka
      run: sudo apt-get install -y libcmocka-dev
    # install glibc
    - name: install glibc
      run: sudo apt-get install -y libc6-dev
    - name: make
      run: make
