name: Build and release assets

on:
  push:
    branches: [ "builds" ]
    tags: [ "v*" ]

jobs:
  build:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [macos-latest]
        arch: [x86_64, aarch64]
        include:
          - platform: macos-latest
            arch: x86_64
          - platform: macos-latest
            arch: aarch64

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ARCH: ${{ matrix.arch }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add dependencies
        run: |
          brew install cmocka
          brew install glib

      - name: Build the project
        run: make build TARGET=${{ env.TARGET }}

      - name: Publish the tarball release
        run: make tarball-publish TARGET=${{ env.TARGET }}
